<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/SOATutorialsWin11/BillingManagementSystem/bmsSchema"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:tns="http://xmlns.oracle.com/SOATutorialsWin11/BillingManagementSystem/bmsInterface"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/BillingManagementSystem/WSDLs/bmsInterface.wsdl"/>
        <oracle-xsl-mapper:rootElement name="bmsRequestSchema"
                                       namespace="http://xmlns.oracle.com/SOATutorialsWin11/BillingManagementSystem/bmsSchema"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/BillingManagementSystem/WSDLs/bmsInterface.wsdl"/>
        <oracle-xsl-mapper:rootElement name="bmsCallbackSchema"
                                       namespace="http://xmlns.oracle.com/SOATutorialsWin11/BillingManagementSystem/bmsSchema"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI NOV 22 15:38:06 EAT 2024].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:bmsCallbackSchema>
      <xsl:for-each select="/ns0:bmsRequestSchema/ns0:itemDetails">
        <ns0:itemDetails>
          <ns0:itemName>
            <xsl:value-of select="ns0:itemName"/>
          </ns0:itemName>
          <ns0:itemCost>
            <xsl:value-of select="ns0:itemCost"/>
          </ns0:itemCost>
        </ns0:itemDetails>
      </xsl:for-each>
      <ns0:orderTotalCost>
        <xsl:value-of select="sum (/ns0:bmsRequestSchema/ns0:itemDetails/ns0:itemCost )"/>
      </ns0:orderTotalCost>
    </ns0:bmsCallbackSchema>
  </xsl:template>
</xsl:stylesheet>
