create or replace package XX_BPEL_FND_REQUEST_WRAPPER
is
   procedure submit_request(REQUEST_ID OUT NUMBER, 
                            RETURN_CODE OUT VARCHAR2,
                            RETURN_MESSAGE OUT VARCHAR2,
                            application IN varchar2 default NULL,
                            program     IN varchar2 default NULL,
                            description IN varchar2 default NULL,
                            start_time  IN varchar2 default NULL,
                            sub_request IN integer,
                            argument1   IN varchar2 default CHR(0),
                            argument2   IN varchar2 default CHR(0),
                            argument3   IN varchar2 default CHR(0),
                            argument4   IN varchar2 default CHR(0),
                            argument5   IN varchar2 default CHR(0),
                            argument6   IN varchar2 default CHR(0),
                            argument7   IN varchar2 default CHR(0),
                            argument8   IN varchar2 default CHR(0),
                            argument9   IN varchar2 default CHR(0),
                            argument10  IN varchar2 default CHR(0),
                            argument11  IN varchar2 default CHR(0),
                            argument12  IN varchar2 default CHR(0),
                            argument13  IN varchar2 default CHR(0),
                            argument14  IN varchar2 default CHR(0),
                            argument15  IN varchar2 default CHR(0),
                            argument16  IN varchar2 default CHR(0),
                            argument17  IN varchar2 default CHR(0),
                            argument18  IN varchar2 default CHR(0),
                            argument19  IN varchar2 default CHR(0),
                            argument20  IN varchar2 default CHR(0),
                            argument21  IN varchar2 default CHR(0),
                            argument22  IN varchar2 default CHR(0),
                            argument23  IN varchar2 default CHR(0),
                            argument24  IN varchar2 default CHR(0),
                            argument25  IN varchar2 default CHR(0),
                            argument26  IN varchar2 default CHR(0),
                            argument27  IN varchar2 default CHR(0),
                            argument28  IN varchar2 default CHR(0),
                            argument29  IN varchar2 default CHR(0),
                            argument30  IN varchar2 default CHR(0),
                            argument31  IN varchar2 default CHR(0),
                            argument32  IN varchar2 default CHR(0),
                            argument33  IN varchar2 default CHR(0),
                            argument34  IN varchar2 default CHR(0),
                            argument35  IN varchar2 default CHR(0),
                            argument36  IN varchar2 default CHR(0),
                            argument37  IN varchar2 default CHR(0),
                            argument38  IN varchar2 default CHR(0),
                            argument39  IN varchar2 default CHR(0),
                            argument40  IN varchar2 default CHR(0),
                            argument41  IN varchar2 default CHR(0),
                            argument42  IN varchar2 default CHR(0),
                            argument43  IN varchar2 default CHR(0),
                            argument44  IN varchar2 default CHR(0),
                            argument45  IN varchar2 default CHR(0),
                            argument46  IN varchar2 default CHR(0),
                            argument47  IN varchar2 default CHR(0),
                            argument48  IN varchar2 default CHR(0),
                            argument49  IN varchar2 default CHR(0),
                            argument50  IN varchar2 default CHR(0),
                            argument51  IN varchar2 default CHR(0),
                            argument52  IN varchar2 default CHR(0),
                            argument53  IN varchar2 default CHR(0),
                            argument54  IN varchar2 default CHR(0),
                            argument55  IN varchar2 default CHR(0),
                            argument56  IN varchar2 default CHR(0),
                            argument57  IN varchar2 default CHR(0),
                            argument58  IN varchar2 default CHR(0),
                            argument59  IN varchar2 default CHR(0),
                            argument60  IN varchar2 default CHR(0),
                            argument61  IN varchar2 default CHR(0),
                            argument62  IN varchar2 default CHR(0),
                            argument63  IN varchar2 default CHR(0),
                            argument64  IN varchar2 default CHR(0),
                            argument65  IN varchar2 default CHR(0),
                            argument66  IN varchar2 default CHR(0),
                            argument67  IN varchar2 default CHR(0),
                            argument68  IN varchar2 default CHR(0),
                            argument69  IN varchar2 default CHR(0),
                            argument70  IN varchar2 default CHR(0),
                            argument71  IN varchar2 default CHR(0),
                            argument72  IN varchar2 default CHR(0),
                            argument73  IN varchar2 default CHR(0),
                            argument74  IN varchar2 default CHR(0),
                            argument75  IN varchar2 default CHR(0),
                            argument76  IN varchar2 default CHR(0),
                            argument77  IN varchar2 default CHR(0),
                            argument78  IN varchar2 default CHR(0),
                            argument79  IN varchar2 default CHR(0),
                            argument80  IN varchar2 default CHR(0),
                            argument81  IN varchar2 default CHR(0),
                            argument82  IN varchar2 default CHR(0),
                            argument83  IN varchar2 default CHR(0),
                            argument84  IN varchar2 default CHR(0),
                            argument85  IN varchar2 default CHR(0),
                            argument86  IN varchar2 default CHR(0),
                            argument87  IN varchar2 default CHR(0),
                            argument88  IN varchar2 default CHR(0),
                            argument89  IN varchar2 default CHR(0),
                            argument90  IN varchar2 default CHR(0),
                            argument91  IN varchar2 default CHR(0),
                            argument92  IN varchar2 default CHR(0),
                            argument93  IN varchar2 default CHR(0),
                            argument94  IN varchar2 default CHR(0),
                            argument95  IN varchar2 default CHR(0),
                            argument96  IN varchar2 default CHR(0),
                            argument97  IN varchar2 default CHR(0),
                            argument98  IN varchar2 default CHR(0),
                            argument99  IN varchar2 default CHR(0),
                            argument100  IN varchar2 default CHR(0));

end;
/
create or replace package body XX_BPEL_FND_REQUEST_WRAPPER
is
    procedure submit_request(REQUEST_ID OUT NUMBER, 
                            RETURN_CODE OUT VARCHAR2,
                            RETURN_MESSAGE OUT VARCHAR2,
                            application IN varchar2 default NULL,
                            program     IN varchar2 default NULL,
                            description IN varchar2 default NULL,
                            start_time  IN varchar2 default NULL,
                            sub_request IN integer,
                            argument1   IN varchar2 default CHR(0),
                            argument2   IN varchar2 default CHR(0),
                            argument3   IN varchar2 default CHR(0),
                            argument4   IN varchar2 default CHR(0),
                            argument5   IN varchar2 default CHR(0),
                            argument6   IN varchar2 default CHR(0),
                            argument7   IN varchar2 default CHR(0),
                            argument8   IN varchar2 default CHR(0),
                            argument9   IN varchar2 default CHR(0),
                            argument10  IN varchar2 default CHR(0),
                            argument11  IN varchar2 default CHR(0),
                            argument12  IN varchar2 default CHR(0),
                            argument13  IN varchar2 default CHR(0),
                            argument14  IN varchar2 default CHR(0),
                            argument15  IN varchar2 default CHR(0),
                            argument16  IN varchar2 default CHR(0),
                            argument17  IN varchar2 default CHR(0),
                            argument18  IN varchar2 default CHR(0),
                            argument19  IN varchar2 default CHR(0),
                            argument20  IN varchar2 default CHR(0),
                            argument21  IN varchar2 default CHR(0),
                            argument22  IN varchar2 default CHR(0),
                            argument23  IN varchar2 default CHR(0),
                            argument24  IN varchar2 default CHR(0),
                            argument25  IN varchar2 default CHR(0),
                            argument26  IN varchar2 default CHR(0),
                            argument27  IN varchar2 default CHR(0),
                            argument28  IN varchar2 default CHR(0),
                            argument29  IN varchar2 default CHR(0),
                            argument30  IN varchar2 default CHR(0),
                            argument31  IN varchar2 default CHR(0),
                            argument32  IN varchar2 default CHR(0),
                            argument33  IN varchar2 default CHR(0),
                            argument34  IN varchar2 default CHR(0),
                            argument35  IN varchar2 default CHR(0),
                            argument36  IN varchar2 default CHR(0),
                            argument37  IN varchar2 default CHR(0),
                            argument38  IN varchar2 default CHR(0),
                            argument39  IN varchar2 default CHR(0),
                            argument40  IN varchar2 default CHR(0),
                            argument41  IN varchar2 default CHR(0),
                            argument42  IN varchar2 default CHR(0),
                            argument43  IN varchar2 default CHR(0),
                            argument44  IN varchar2 default CHR(0),
                            argument45  IN varchar2 default CHR(0),
                            argument46  IN varchar2 default CHR(0),
                            argument47  IN varchar2 default CHR(0),
                            argument48  IN varchar2 default CHR(0),
                            argument49  IN varchar2 default CHR(0),
                            argument50  IN varchar2 default CHR(0),
                            argument51  IN varchar2 default CHR(0),
                            argument52  IN varchar2 default CHR(0),
                            argument53  IN varchar2 default CHR(0),
                            argument54  IN varchar2 default CHR(0),
                            argument55  IN varchar2 default CHR(0),
                            argument56  IN varchar2 default CHR(0),
                            argument57  IN varchar2 default CHR(0),
                            argument58  IN varchar2 default CHR(0),
                            argument59  IN varchar2 default CHR(0),
                            argument60  IN varchar2 default CHR(0),
                            argument61  IN varchar2 default CHR(0),
                            argument62  IN varchar2 default CHR(0),
                            argument63  IN varchar2 default CHR(0),
                            argument64  IN varchar2 default CHR(0),
                            argument65  IN varchar2 default CHR(0),
                            argument66  IN varchar2 default CHR(0),
                            argument67  IN varchar2 default CHR(0),
                            argument68  IN varchar2 default CHR(0),
                            argument69  IN varchar2 default CHR(0),
                            argument70  IN varchar2 default CHR(0),
                            argument71  IN varchar2 default CHR(0),
                            argument72  IN varchar2 default CHR(0),
                            argument73  IN varchar2 default CHR(0),
                            argument74  IN varchar2 default CHR(0),
                            argument75  IN varchar2 default CHR(0),
                            argument76  IN varchar2 default CHR(0),
                            argument77  IN varchar2 default CHR(0),
                            argument78  IN varchar2 default CHR(0),
                            argument79  IN varchar2 default CHR(0),
                            argument80  IN varchar2 default CHR(0),
                            argument81  IN varchar2 default CHR(0),
                            argument82  IN varchar2 default CHR(0),
                            argument83  IN varchar2 default CHR(0),
                            argument84  IN varchar2 default CHR(0),
                            argument85  IN varchar2 default CHR(0),
                            argument86  IN varchar2 default CHR(0),
                            argument87  IN varchar2 default CHR(0),
                            argument88  IN varchar2 default CHR(0),
                            argument89  IN varchar2 default CHR(0),
                            argument90  IN varchar2 default CHR(0),
                            argument91  IN varchar2 default CHR(0),
                            argument92  IN varchar2 default CHR(0),
                            argument93  IN varchar2 default CHR(0),
                            argument94  IN varchar2 default CHR(0),
                            argument95  IN varchar2 default CHR(0),
                            argument96  IN varchar2 default CHR(0),
                            argument97  IN varchar2 default CHR(0),
                            argument98  IN varchar2 default CHR(0),
                            argument99  IN varchar2 default CHR(0),
                            argument100  IN varchar2 default CHR(0)
)
is
	L_SUB_REQUEST BOOLEAN := FALSE;
begin
      L_SUB_REQUEST := SYS.SQLJUTL.INT2BOOL(SUB_REQUEST);
      REQUEST_ID := FND_REQUEST.SUBMIT_REQUEST(APPLICATION,PROGRAM,DESCRIPTION,START_TIME,L_SUB_REQUEST,ARGUMENT1,ARGUMENT2,ARGUMENT3,ARGUMENT4,ARGUMENT5,ARGUMENT6,ARGUMENT7,ARGUMENT8,ARGUMENT9,ARGUMENT10,ARGUMENT11,ARGUMENT12,ARGUMENT13,ARGUMENT14,ARGUMENT15,
      ARGUMENT16,ARGUMENT17,ARGUMENT18,ARGUMENT19,ARGUMENT20,ARGUMENT21,ARGUMENT22,ARGUMENT23,ARGUMENT24,ARGUMENT25,ARGUMENT26,ARGUMENT27,ARGUMENT28,ARGUMENT29,ARGUMENT30,ARGUMENT31,ARGUMENT32,ARGUMENT33,ARGUMENT34,ARGUMENT35,ARGUMENT36,ARGUMENT37,ARGUMENT38,ARGUMENT39,ARGUMENT40,ARGUMENT41,ARGUMENT42,ARGUMENT43,ARGUMENT44,ARGUMENT45,ARGUMENT46,ARGUMENT47,
      ARGUMENT48,ARGUMENT49,ARGUMENT50,ARGUMENT51,ARGUMENT52,ARGUMENT53,ARGUMENT54,ARGUMENT55,ARGUMENT56,ARGUMENT57,ARGUMENT58,ARGUMENT59,ARGUMENT60,ARGUMENT61,ARGUMENT62,ARGUMENT63,ARGUMENT64,ARGUMENT65,ARGUMENT66,ARGUMENT67,ARGUMENT68,ARGUMENT69,ARGUMENT70,ARGUMENT71,ARGUMENT72,ARGUMENT73,ARGUMENT74,ARGUMENT75,ARGUMENT76,ARGUMENT77,ARGUMENT78,ARGUMENT79,
      ARGUMENT80,ARGUMENT81,ARGUMENT82,ARGUMENT83,ARGUMENT84,ARGUMENT85,ARGUMENT86,ARGUMENT87,ARGUMENT88,ARGUMENT89,ARGUMENT90,ARGUMENT91,ARGUMENT92,ARGUMENT93,ARGUMENT94,ARGUMENT95,ARGUMENT96,ARGUMENT97,ARGUMENT98,ARGUMENT99,ARGUMENT100);
      if REQUEST_ID = 0 then
          RETURN_CODE := '2';
          RETURN_MESSAGE := fnd_message.get;
      else
          RETURN_CODE := '0';
      end if;
end submit_request;
end;
/
